use anyhow::{Context, Result};
use forgen_api::{FileReplacement, Plugin, WorkspaceContext};
use libloading::{Library, Symbol};
use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use std::path::Path;

// C-ABI function pointer types matching the signatures generated by `plugin_export!`.
type ForgenPluginNameFn = unsafe extern "C" fn() -> *const c_char;
type ForgenRunFn = unsafe extern "C" fn(*const c_char) -> *mut c_char;
type ForgenFreeFn = unsafe extern "C" fn(*mut c_char);

/// A Forgen plugin loaded from a dynamic library (`.dll` / `.so` / `.dylib`).
///
/// Implements [`Plugin`] by serialising the [`WorkspaceContext`] to JSON,
/// calling the library's `forgen_run` symbol, and deserialising the returned
/// JSON back into `Vec<FileReplacement>`.
///
/// The [`Library`] is kept alive for the entire lifetime of this struct, so
/// the raw function pointers stored here remain valid.
pub struct DylibPlugin {
    /// Keeps the shared library mapped into memory.
    _lib: Library,
    /// Human-readable name returned by `forgen_plugin_name`.
    name: String,
    /// Raw pointer to the `forgen_run` entry point.
    run_fn: ForgenRunFn,
    /// Raw pointer to the `forgen_free` entry point.
    free_fn: ForgenFreeFn,
}

impl DylibPlugin {
    /// Load and validate a Forgen plugin from a shared-library file.
    ///
    /// # Errors
    ///
    /// Returns an error if the file cannot be opened, or if any of the
    /// three required symbols (`forgen_plugin_name`, `forgen_run`,
    /// `forgen_free`) are missing.
    ///
    /// # Safety
    ///
    /// The library *must* export the three symbols with the exact signatures
    /// generated by `forgen_api::plugin_export!`. Passing a library that does
    /// not honour the ABI contract is undefined behaviour.
    pub unsafe fn load(path: &Path) -> Result<Self> {
        let lib = Library::new(path)
            .with_context(|| format!("Failed to open plugin library: {}", path.display()))?;

        // Resolve all three symbols while we still have `Symbol` values bound
        // to `lib`. We immediately dereference each symbol into a bare function
        // pointer so we are not burdened by the `Symbol`'s lifetime after this
        // block; safety is maintained because `_lib` keeps the library loaded.
        let name_fn: ForgenPluginNameFn = {
            let sym: Symbol<ForgenPluginNameFn> =
                lib.get(b"forgen_plugin_name\0").with_context(|| {
                    format!(
                        "Plugin '{}' is missing the `forgen_plugin_name` symbol",
                        path.display()
                    )
                })?;
            *sym
        };

        let run_fn: ForgenRunFn = {
            let sym: Symbol<ForgenRunFn> = lib.get(b"forgen_run\0").with_context(|| {
                format!(
                    "Plugin '{}' is missing the `forgen_run` symbol",
                    path.display()
                )
            })?;
            *sym
        };

        let free_fn: ForgenFreeFn = {
            let sym: Symbol<ForgenFreeFn> = lib.get(b"forgen_free\0").with_context(|| {
                format!(
                    "Plugin '{}' is missing the `forgen_free` symbol",
                    path.display()
                )
            })?;
            *sym
        };

        // Read the plugin's self-reported name.
        let name = {
            let ptr = name_fn();
            if ptr.is_null() {
                path.file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("unknown")
                    .to_owned()
            } else {
                CStr::from_ptr(ptr).to_str().unwrap_or("unknown").to_owned()
            }
        };

        Ok(Self {
            _lib: lib,
            name,
            run_fn,
            free_fn,
        })
    }
}

impl Plugin for DylibPlugin {
    fn name(&self) -> &str {
        &self.name
    }

    fn run(&self, ctx: &WorkspaceContext) -> Vec<FileReplacement> {
        // Serialise the workspace context to JSON.
        let json = match serde_json::to_string(ctx) {
            Ok(j) => j,
            Err(e) => {
                eprintln!(
                    "  ⚠️  [{}] Failed to serialise WorkspaceContext: {}",
                    self.name, e
                );
                return vec![];
            }
        };

        // Convert to a null-terminated C string.
        let c_json = match CString::new(json) {
            Ok(s) => s,
            Err(e) => {
                eprintln!(
                    "  ⚠️  [{}] WorkspaceContext JSON contains a null byte: {}",
                    self.name, e
                );
                return vec![];
            }
        };

        // Call the plugin.
        // Safety: `run_fn` was resolved from the library and the library is
        // still loaded. `c_json.as_ptr()` is valid for the duration of the call.
        let result_ptr = unsafe { (self.run_fn)(c_json.as_ptr()) };

        if result_ptr.is_null() {
            eprintln!("  ⚠️  [{}] forgen_run returned a null pointer", self.name);
            return vec![];
        }

        // Read the result before freeing.
        // Safety: the plugin guarantees the pointer is a valid, null-terminated
        // UTF-8 C string until `forgen_free` is called.
        let result_str = unsafe { CStr::from_ptr(result_ptr) }
            .to_str()
            .unwrap_or("[]")
            .to_owned();

        // Free the plugin-allocated string.
        // Safety: `result_ptr` was returned by `forgen_run` and has not been
        // freed yet.
        unsafe { (self.free_fn)(result_ptr) };

        // Deserialise the result.
        match serde_json::from_str::<Vec<FileReplacement>>(&result_str) {
            Ok(replacements) => replacements,
            Err(e) => {
                eprintln!(
                    "  ⚠️  [{}] Failed to deserialise plugin result: {}",
                    self.name, e
                );
                vec![]
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Directory scanner
// ---------------------------------------------------------------------------

/// Load every Forgen plugin found in `dir`.
///
/// Files whose extension matches the current platform's shared-library
/// convention (`.dll` on Windows, `.so` on Linux, `.dylib` on macOS) are
/// treated as candidate plugins. Any file that cannot be loaded or is missing
/// the required symbols is skipped with a warning — it does not abort the
/// whole run.
///
/// Returns an empty `Vec` (without error) if the directory does not exist or
/// contains no loadable plugins.
pub fn load_plugins_from_dir(dir: &Path) -> Vec<Box<dyn Plugin>> {
    let mut plugins: Vec<Box<dyn Plugin>> = Vec::new();

    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            eprintln!(
                "  ⚠️  Could not read plugin directory '{}': {}",
                dir.display(),
                e
            );
            return plugins;
        }
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if !is_plugin_lib(&path) {
            continue;
        }

        match unsafe { DylibPlugin::load(&path) } {
            Ok(plugin) => {
                println!(
                    "  🔌 Loaded dylib plugin '{}' from {}",
                    plugin.name(),
                    path.display()
                );
                plugins.push(Box::new(plugin));
            }
            Err(e) => {
                eprintln!("  ⚠️  Skipping '{}': {}", path.display(), e);
            }
        }
    }

    plugins
}

/// Returns `true` if `path` has the platform-native shared-library extension.
fn is_plugin_lib(path: &Path) -> bool {
    let Some(ext) = path.extension().and_then(|e| e.to_str()) else {
        return false;
    };

    #[cfg(target_os = "windows")]
    return ext.eq_ignore_ascii_case("dll");

    #[cfg(target_os = "macos")]
    return ext.eq_ignore_ascii_case("dylib");

    #[cfg(not(any(target_os = "windows", target_os = "macos")))]
    return ext.eq_ignore_ascii_case("so");
}

