use anyhow::{Context, Result};
use forgen_api::{FileReplacement, Plugin, WorkspaceContext, FORGEN_ABI_VERSION};
use libloading::{Library, Symbol};
use std::path::{Path, PathBuf};
use std::process::Command;

// ---------------------------------------------------------------------------
// Raw-pointer ABI types
//
// These match exactly what `plugin_suite!` generates in forgen-api.
// No JSON, no C strings — the CLI passes a *const WorkspaceContext directly
// into the dylib and gets a *mut Vec<FileReplacement> back.
// ---------------------------------------------------------------------------

type ForgenAbiVersionFn = unsafe extern "C" fn() -> u64;
type ForgenRunFn = unsafe extern "C" fn(*const WorkspaceContext) -> *mut Vec<FileReplacement>;
type ForgenFreeFn = unsafe extern "C" fn(*mut Vec<FileReplacement>);

// ---------------------------------------------------------------------------
// PluginSuite
// ---------------------------------------------------------------------------

/// A loaded plugin suite dylib, wrapped as a [`Plugin`].
///
/// The plugin suite is the **single** shared library that the CLI loads per
/// workspace run.  Inside the dylib, plugin crates are called as plain Rust
/// function calls — no FFI, no serialisation.  Only the boundary between the
/// CLI binary and this dylib uses FFI, and it is zero-copy: the CLI passes a
/// raw pointer to its stack-allocated `WorkspaceContext` and reads the result
/// directly through a `Box`-backed pointer.
///
/// # Safety contract
///
/// Both the CLI and the plugin suite dylib must:
///
/// - Be compiled with the **same version** of `forgen-api` (the ABI version
///   handshake enforces this at load time).
/// - Use the **system allocator** — neither crate may set a custom
///   `#[global_allocator]`.  This ensures that `Box::from_raw` across the
///   boundary is sound (both sides call the same underlying `malloc`/`free`).
pub struct PluginSuite {
    /// Keeps the shared library mapped into memory for the entire lifetime of
    /// this struct so that the function pointers below remain valid.
    _lib: Library,
    /// Human-readable name derived from the dylib file stem.
    name: String,
    /// Raw pointer to `forgen_run` — receives `*const WorkspaceContext`,
    /// returns `*mut Vec<FileReplacement>`.
    run_fn: ForgenRunFn,
    /// Raw pointer to `forgen_free` — frees the `Vec<FileReplacement>` that
    /// was returned by `forgen_run`.  Kept as a fallback; the default `run`
    /// impl uses `Box::from_raw` instead (same allocator on both sides).
    #[allow(dead_code)]
    free_fn: ForgenFreeFn,
}

impl PluginSuite {
    /// Load and validate a plugin suite dylib from `path`.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The library cannot be opened.
    /// - Any of the three required symbols are missing.
    /// - The ABI version reported by the dylib does not match
    ///   [`FORGEN_ABI_VERSION`].
    ///
    /// # Safety
    ///
    /// The library must export `forgen_abi_version`, `forgen_run`, and
    /// `forgen_free` with the exact signatures generated by
    /// `forgen_api::plugin_suite!`.
    pub unsafe fn load(path: &Path) -> Result<Self> {
        let lib = Library::new(path)
            .with_context(|| format!("Failed to open plugin suite: {}", path.display()))?;

        // ── ABI version handshake ────────────────────────────────────────
        //
        // Resolve the version symbol while we still hold a `Symbol` (which
        // borrows `lib`), then immediately call it and drop the symbol so
        // that `lib` is no longer borrowed for the rest of this function.
        let dylib_version: u64 = {
            let sym: Symbol<ForgenAbiVersionFn> =
                lib.get(b"forgen_abi_version\0").with_context(|| {
                    format!(
                        "Plugin suite '{}' is missing `forgen_abi_version`.\n\
                         Make sure it uses `forgen_api::plugin_suite!`.",
                        path.display()
                    )
                })?;
            sym()
        };

        if dylib_version != FORGEN_ABI_VERSION {
            anyhow::bail!(
                "ABI version mismatch for '{}':\n  \
                 CLI compiled with forgen-api ABI {}, \
                 plugin suite was compiled with ABI {}.\n  \
                 Run `cargo install --path ./cli` to reinstall cargo-forgen, \
                 or update `forgen-api` in your workspace to match.",
                path.display(),
                FORGEN_ABI_VERSION,
                dylib_version,
            );
        }

        // ── Resolve entry points ─────────────────────────────────────────
        //
        // We dereference each `Symbol` into a bare function pointer so we
        // can store them without the `Symbol` lifetime.  This is sound
        // because `_lib` keeps the library loaded for the entire lifetime of
        // `PluginSuite`.

        let run_fn: ForgenRunFn = {
            let sym: Symbol<ForgenRunFn> = lib.get(b"forgen_run\0").with_context(|| {
                format!("Plugin suite '{}' is missing `forgen_run`.", path.display())
            })?;
            *sym
        };

        let free_fn: ForgenFreeFn = {
            let sym: Symbol<ForgenFreeFn> = lib.get(b"forgen_free\0").with_context(|| {
                format!(
                    "Plugin suite '{}' is missing `forgen_free`.",
                    path.display()
                )
            })?;
            *sym
        };

        let name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("suite")
            .to_owned();

        Ok(Self {
            _lib: lib,
            name,
            run_fn,
            free_fn,
        })
    }
}

impl Plugin for PluginSuite {
    fn name(&self) -> &str {
        &self.name
    }

    fn run(&self, ctx: &WorkspaceContext) -> Vec<FileReplacement> {
        // Safety:
        // - `run_fn` is a valid function pointer; `_lib` is alive.
        // - `ctx` is a valid reference for the duration of this call.
        // - The returned pointer was produced by `Box::into_raw` inside the
        //   dylib (via `plugin_suite!`).
        // - Both CLI and dylib use the system allocator, so
        //   `Box::from_raw` here correctly pairs with the dylib's `Box::new`.
        let ptr = unsafe { (self.run_fn)(ctx as *const WorkspaceContext) };

        if ptr.is_null() {
            return Vec::new();
        }

        // Move the `Vec<FileReplacement>` out of the Box.  The Box wrapper
        // is freed here (on the CLI side); the Vec contents (Strings, inner
        // Vecs) will be freed when `result` is eventually dropped.  Both
        // frees go through the system allocator, which is shared.
        unsafe { *Box::from_raw(ptr) }
    }
}

// ---------------------------------------------------------------------------
// Plugin suite loader
// ---------------------------------------------------------------------------

/// Reads `[workspace.metadata.forgen] suite = "<name>"` from the
/// cargo metadata, builds that crate with `cargo build`, and loads the
/// resulting shared library as a [`PluginSuite`].
///
/// Returns `None` (without error) if the key is absent — meaning the user
/// has not configured a plugin suite yet and only built-in plugins run.
pub fn load_suite(meta: &cargo_metadata::Metadata) -> Option<Box<dyn Plugin>> {
    // Explicit config takes priority.  If absent, fall back to auto-discovery:
    // a workspace member named "plugins" is treated as the plugin suite by
    // convention (no Cargo.toml entry required).
    let suite_name = meta
        .workspace_metadata
        .get("forgen")
        .and_then(|f| f.get("suite"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_owned())
        .or_else(|| {
            // Auto-discover a workspace member called "plugins".
            meta.workspace_packages()
                .iter()
                .any(|p| p.name == "plugins")
                .then(|| "plugins".to_owned())
        })?; // return None if neither configured nor auto-discovered

    let workspace_root: &Path = meta.workspace_root.as_std_path();
    let target_dir: &Path = meta.target_directory.as_std_path();

    println!("  🔨 Building plugin suite '{suite_name}'...");

    // Build the plugin suite crate as a cdylib.
    // We suppress output on the first attempt; if the build fails we re-run
    // with inherited stdio so the user sees the compiler errors.
    let silent_status = Command::new("cargo")
        .args(["build", "--package", &suite_name])
        .current_dir(workspace_root)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();

    match silent_status {
        Ok(s) if s.success() => { /* all good */ }
        Ok(_) => {
            eprintln!(
                "  ⚠️  `cargo build --package {suite_name}` failed — \
                 re-running with output:"
            );
            let _ = Command::new("cargo")
                .args(["build", "--package", &suite_name])
                .current_dir(workspace_root)
                .status();
            return None;
        }
        Err(e) => {
            eprintln!("  ⚠️  Failed to invoke `cargo build`: {e}");
            return None;
        }
    }

    // Locate the compiled dylib in target/debug/.
    let lib_stem = suite_name.replace('-', "_");
    let Some(dylib_path) = dylib_path_in_target(target_dir, &lib_stem) else {
        eprintln!(
            "  ⚠️  Build succeeded but no dylib found for '{suite_name}' in {}.\n  \
             Make sure your Cargo.toml has `crate-type = [\"cdylib\"]`.",
            target_dir.join("debug").display()
        );
        return None;
    };

    match unsafe { PluginSuite::load(&dylib_path) } {
        Ok(p) => {
            println!(
                "  ✅ Loaded plugin suite '{}' from {}",
                p.name(),
                dylib_path.display()
            );
            Some(Box::new(p))
        }
        Err(e) => {
            eprintln!("  ⚠️  {e}");
            None
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Returns the expected on-disk path of the `cdylib` output for `lib_stem`
/// (underscores, not hyphens) inside `<target_dir>/debug/`.
///
/// Returns `None` if the file does not yet exist.
fn dylib_path_in_target(target_dir: &Path, lib_stem: &str) -> Option<PathBuf> {
    let debug_dir = target_dir.join("debug");

    #[cfg(target_os = "windows")]
    let filename = format!("{lib_stem}.dll");

    #[cfg(target_os = "macos")]
    let filename = format!("lib{lib_stem}.dylib");

    #[cfg(not(any(target_os = "windows", target_os = "macos")))]
    let filename = format!("lib{lib_stem}.so");

    let path = debug_dir.join(filename);
    path.exists().then_some(path)
}
